### ISSUE TITLE
Can I get it to use `standard`?

### ISSUE THREAD

**Issue by laduke** [aaronjensen/eslintd-fix#10]
Thanks for all your js emacs stuff. 

A lot of the time, my only linter config is just having `standard` in devDependencies, so there's not eslint conf file in the project. I think eslintd-fix doesn't know how to configure itself/eslintd in this case?  If I run `eslintd -c standard index.js` from the shell, it somehow does the right thing. But I can't figure out how to convince emacs to run it like that, or alternatively to use the `standard` binary.

**Comment by aaronjensen** [comment]
Hi @laduke, You're welcome 😄 

You are right that eslintd-fix hasn't taken `standard` into account. I'm not sure what that would take. Using the `standard` binary wouldn't really work because `eslint_d` has special commands that work with `eslintd-fix`. You'd need another, similar package to this in order to use the `standard` binary unless it shared the same flags as `eslint_d`. 

As you're running `eslint_d -c standard` to get it to do the right thing `eslintd-fix` has no way of knowing that you need to do that. It runs `eslint_d --print-config <filename>` in order to see if that file is configured. You may be able to add an additional args custom var to both that check and the actual invocation of `eslint_d` in order to get it to work.

Does `flycheck-eslint` work out of the box for you?

**Comment by laduke** [comment]
hmm there's a `flycheck-javascript-standard` that's part of flycheck that works. 

```
Syntax checkers for buffer index.js in rjsx-mode:

  javascript-eslint
    - may enable:  Automatically disabled!
    - executable:  Not found
    - config file: missing or incorrect

  javascript-standard
    - may enable: yes
    - executable: Found at /Users/travis/.nvs/default/bin/standard
```

Are you saying fork this and redefine `eslintd-fix--eslint-config-foundp` slightly? Or I could redefine it from my own config?

**Comment by aaronjensen** [comment]
I'd take a PR that allowed for additional args to be passed to invocations of `eslint_d`. 

I'm curious how `eslnit_d -c standard` works though, do you have `eslint-config-standard` installed?

**Comment by laduke** [comment]
>  do you have eslint-config-standard installed?

no! I'm confused how/why that's working. If I don't use that switch, it chokes on some destructuring assignment. 

```
~/s/❯❯❯ eslint_d index.js                                                                                                                                  
  7:5  error  Parsing error: Unexpected token {

~/s/❯❯❯ eslint_d index.js -c standard      
  5:29  error  Extra semicolon  semi
```
🤷‍♀️

> I'd take a PR that allowed for additional args to be passed to invocations of eslint_d.

Oh man, I'll give it a shot!

**Comment by aaronjensen** [comment]
Sounds good. By the way, I'm sure you've considered it, but it'd probably be easier to add an eslint config and call it a day 😄

**Comment by laduke** [comment]
hey, this is the minimal config in a package.json 

```
  "devDependencies": {
    "standard": "^12.0.1"
  },
  "eslintConfig": {
    "extends": "standard"
  }
```
(on dev spacemacs currently)

thanks!
